Fix the build by adding an argument to catch statement
Summary:
Turns out D22722736 (https://github.com/facebook/draft-js/commit/36de6f1f201537d9e21654188bb7483a6b4ae76e) broke the OSS build: apparently `catch` without arguments is a [fairly new feature](https://stackoverflow.com/questions/21624456/can-i-use-a-try-catch-in-javascript-without-specifying-the-catch-argument-identi) that UglifyJS doesn't understand. Whoops. It threw:

```
ERROR: Unexpected token: punc «{», expected: punc «(»
```

Go figure.

It seems unlikey that it's possible, but it'd be cool if the TravisCI build status could block lands in www. There's no way to get signal about this until after the fact. /:

Reviewed By: creedarky

Differential Revision: D22771035

fbshipit-source-id: cd61c6a3ca2aab534c99939a4fb7f29a8863c2ea